### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by UrSanctuary** [UrSanctuary/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by YLITID** [comment]
Donald J. Trump is the 45th President of the United States. I believe the United States has incredible potential and will go on to exceed even its remarkable achievements of the past.
I define the American success story. Throughout my life I has continually set the standards of business and entrepreneurial excellence, especially in real estate, sports, and entertainment. I am Mr. Trump who built on my success in private life when he entered into politics and public service. I remarkably won the Presidency in his first ever run for any political office.

**Comment by UrSanctuary** [comment]
Дякую)
