### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by UrSanctuary** [UrSanctuary/homepage#8]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by YLITID** [comment]
https://www.facebook.com/DonaldTrump/
https://www.instagram.com/realdonaldtrump/
https://twitter.com/donaldtrump

**Comment by UrSanctuary** [comment]
Трохи помучу тебе ще, із заповненням інфи
